### ISSUE TITLE
slow perf?

### ISSUE THREAD

**Issue by jeremy-coleman** [dan-lee/glamor-jss#38]
I ran the test suite for ops/sec, in both node and the browser, and got crazy slow results compared to glamor and emotion. node was 6k: glamor-jss 13k glamor, 40k emotion, browser was 140 glamor-jss 100 glamor and 7k emotion (ops/s). are those numbers misleading somehow?

**Comment by jeremy-coleman** [comment]
What counts as an op/s though? Like glamor and jss both use caching so if they do a comparison and use the cached version, will that show as an op? 100 vs 7k seems like maybe the bench isnt comparing apples to apples

**Comment by kof** [comment]
I have strong feeling that its the hashing. Also 6k vs 13k is not crazy slow, it is only 2x slower on a micro benchmark, which could be already a result of a single small suboptimal call.

**Comment by jeremy-coleman** [comment]
140 vs 7k is though, but i also read an isse about instantiating jss , but im not sure how that accounts for glamor as well

**Comment by kof** [comment]
if glamor scores 100 vs 7k emotion on the same benchmark, something is wrong with the benchmark, it does something naively wrong that deoptimizes everything.

**Comment by dan-lee** [comment]
I removed the performance benchmarks now, as @kof said I think they were flawed and not well thought through. I might take another stab at them
